package com.me.tft_02.ghosts.datatypes;

public enum StatsType {
    DEATHS,
    FIND_TOMB,
    RESURRECTION_SCROLLS_USED_T1,
    RESURRECTION_SCROLLS_USED_T2,
    RESURRECTION_SCROLLS_USED_T3,
    RESURRECTION_SCROLLS_USED_OTHERS_T1,
    RESURRECTION_SCROLLS_USED_OTHERS_T2,
    RESURRECTION_SCROLLS_USED_OTHERS_T3,
    RESURRECTION_SCROLLS_RECEIVED_T1,
    RESURRECTION_SCROLLS_RECEIVED_T2,
    RESURRECTION_SCROLLS_RECEIVED_T3,
    GIVEN_UP;
}
