package com.me.tft_02.ghosts.datatypes;

public enum StatsType {
    DEATHS,
    FIND_TOMB,
    RESS_SCROLL_USED_T1,
    RESS_SCROLL_USED_T2,
    RESS_SCROLL_USED_T3,
    RESS_SCROLL_USED_OTHERS_T1,
    RESS_SCROLL_USED_OTHERS_T2,
    RESS_SCROLL_USED_OTHERS_T3,
    RESS_SCROLL_RECEIVED_T1,
    RESS_SCROLL_RECEIVED_T2,
    RESS_SCROLL_RECEIVED_T3,
    GIVEN_UP;
}
